# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interf3.ui'
#
# Created: Wed Sep 07 10:11:45 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from GuiConnections import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object, GuiConnections):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1345, 660)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 861, 601))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(6, -1, 851, 601))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.listWidget = QtGui.QListWidget(self.tab)
        self.listWidget.setGeometry(QtCore.QRect(-5, -9, 141, 591))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.graphicsView = QtGui.QGraphicsView(self.tab)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setGeometry(QtCore.QRect(140, 0, 711, 541))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(140, 540, 711, 31))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pushButton_13 = QtGui.QPushButton(self.frame_3)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 0, 120, 31))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_6 = QtGui.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(236, 1, 59, 31))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(299, 9, 128, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox.setGeometry(QtCore.QRect(140, 0, 62, 31))
        self.doubleSpinBox.setProperty(_fromUtf8("value"), 8.0)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(80, 10, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(210, 10, 31, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_12 = QtGui.QPushButton(self.frame_3)
        self.pushButton_12.setGeometry(QtCore.QRect(609, 0, 92, 31))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_15 = QtGui.QPushButton(self.frame_3)
        self.pushButton_15.setGeometry(QtCore.QRect(426, 0, 65, 31))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(330, 1, 49, 29))
        self.doubleSpinBox_9.setDecimals(2)
        self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.listWidget_2 = QtGui.QListWidget(self.tab_2)
        self.listWidget_2.setGeometry(QtCore.QRect(-5, -9, 141, 591))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(140, 540, 701, 31))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.pushButton_4 = QtGui.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 71, 31))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(140, 500, 411, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_5 = QtGui.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 520, 151, 21))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.graphicsView_2 = QtGui.QGraphicsView(self.tab_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(460, 490, 81, 71))
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.spinBox_4 = QtGui.QSpinBox(self.tab_2)
        self.spinBox_4.setGeometry(QtCore.QRect(350, 520, 51, 22))
        self.spinBox_4.setProperty(_fromUtf8("value"), 1)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(300, 520, 46, 13))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(410, 520, 46, 13))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 600, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 0, 491, 21))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(860, 20, 491, 47))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalSlider = QtGui.QSlider(self.frame_5)
        self.horizontalSlider.setGeometry(QtCore.QRect(75, 21, 272, 20))
        self.horizontalSlider.setMinimum(50)
        self.horizontalSlider.setMaximum(255)
        self.horizontalSlider.setProperty(_fromUtf8("value"), 180)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.label_14 = QtGui.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(7, 24, 61, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.spinBox = QtGui.QSpinBox(self.frame_5)
        self.spinBox.setGeometry(QtCore.QRect(431, 22, 42, 16))
        self.spinBox.setMaximum(10)
        self.spinBox.setProperty(_fromUtf8("value"), 1)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_16 = QtGui.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(367, 22, 61, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_21 = QtGui.QLabel(self.frame_5)
        self.label_21.setGeometry(QtCore.QRect(9, 0, 81, 22))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(860, 444, 491, 167))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.frame_2 = QtGui.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(0, -10, 491, 152))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 31, 91, 117))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(0, 10, 61, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(413, 107, 67, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(228, 32, 54, 22))
        self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
        self.label_13 = QtGui.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(236, 12, 31, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(165, 124, 53, 22))
        self.doubleSpinBox_4.setDecimals(3)
        self.doubleSpinBox_4.setMaximum(999.99)
        self.doubleSpinBox_4.setProperty(_fromUtf8("value"), 1.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(228, 123, 52, 22))
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(229, 104, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_8 = QtGui.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(412, 60, 61, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(409, 127, 71, 22))
        self.doubleSpinBox_5.setMaximum(999.99)
        self.doubleSpinBox_5.setProperty(_fromUtf8("value"), 6.9)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(172, 105, 41, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(410, 79, 68, 22))
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(10000.0)
        self.doubleSpinBox_2.setProperty(_fromUtf8("value"), 632.8)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(180, 13, 24, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(165, 32, 55, 22))
        self.doubleSpinBox_3.setDecimals(3)
        self.doubleSpinBox_3.setMaximum(999.99)
        self.doubleSpinBox_3.setProperty(_fromUtf8("value"), 1.0)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.radioButton = QtGui.QRadioButton(self.frame_2)
        self.radioButton.setGeometry(QtCore.QRect(98, 25, 72, 17))
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.radioButton_2 = QtGui.QRadioButton(self.frame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(100, 53, 69, 17))
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.frame_6 = QtGui.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(100, 106, 61, 41))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.checkBox_2 = QtGui.QRadioButton(self.frame_6)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 20, 51, 17))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox = QtGui.QRadioButton(self.frame_6)
        self.checkBox.setGeometry(QtCore.QRect(0, 0, 51, 17))
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_12.setGeometry(QtCore.QRect(410, 33, 70, 22))
        self.doubleSpinBox_12.setProperty(_fromUtf8("value"), 1.0)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.label_27 = QtGui.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(413, 12, 64, 16))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.frame_8 = QtGui.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(294, 68, 112, 79))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.radioButton_5 = QtGui.QRadioButton(self.frame_8)
        self.radioButton_5.setGeometry(QtCore.QRect(6, 8, 82, 17))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.radioButton_6 = QtGui.QRadioButton(self.frame_8)
        self.radioButton_6.setGeometry(QtCore.QRect(7, 28, 104, 17))
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.radioButton_7 = QtGui.QRadioButton(self.frame_8)
        self.radioButton_7.setGeometry(QtCore.QRect(7, 48, 82, 17))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(296, 14, 54, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(295, 34, 92, 22))
        self.doubleSpinBox_6.setDecimals(5)
        self.doubleSpinBox_6.setMinimum(-999990.0)
        self.doubleSpinBox_6.setMaximum(99999.99)
        self.doubleSpinBox_6.setSingleStep(0.005)
        self.doubleSpinBox_6.setProperty(_fromUtf8("value"), 50.0)
        self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.listWidget_3 = QtGui.QListWidget(self.tab_4)
        self.listWidget_3.setGeometry(QtCore.QRect(80, 17, 81, 120))
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(80, 0, 71, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.pushButton_8 = QtGui.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(411, 120, 71, 21))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_7 = QtGui.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 0, 75, 16))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_9 = QtGui.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(-1, 30, 75, 16))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.line = QtGui.QFrame(self.tab_4)
        self.line.setGeometry(QtCore.QRect(160, 0, 20, 133))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_26 = QtGui.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(170, 0, 91, 16))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.listWidget_5 = QtGui.QListWidget(self.tab_4)
        self.listWidget_5.setGeometry(QtCore.QRect(260, 0, 221, 117))
        self.listWidget_5.setObjectName(_fromUtf8("listWidget_5"))
        self.frame_7 = QtGui.QFrame(self.tab_4)
        self.frame_7.setGeometry(QtCore.QRect(1, 67, 81, 46))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.radioButton_3 = QtGui.QRadioButton(self.frame_7)
        self.radioButton_3.setGeometry(QtCore.QRect(0, 24, 82, 16))
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.radioButton_4 = QtGui.QRadioButton(self.frame_7)
        self.radioButton_4.setGeometry(QtCore.QRect(0, -3, 71, 20))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_11.setGeometry(QtCore.QRect(187, 67, 55, 22))
        self.doubleSpinBox_11.setProperty(_fromUtf8("value"), 1.0)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.label_25 = QtGui.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(194, 40, 31, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_4)
        self.pushButton_2.setGeometry(QtCore.QRect(259, 119, 103, 22))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_10 = QtGui.QPushButton(self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(362, 119, 49, 23))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.tab_4)
        self.pushButton_11.setGeometry(QtCore.QRect(-1, 45, 75, 16))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_14 = QtGui.QPushButton(self.tab_4)
        self.pushButton_14.setGeometry(QtCore.QRect(-1, 15, 76, 16))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1345, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionSet_paths = QtGui.QAction(MainWindow)
        self.actionSet_paths.setObjectName(_fromUtf8("actionSet_paths"))
        self.actionLoad_pictures = QtGui.QAction(MainWindow)
        self.actionLoad_pictures.setObjectName(_fromUtf8("actionLoad_pictures"))
        self.actionLoad_video_file = QtGui.QAction(MainWindow)
        self.actionLoad_video_file.setObjectName(_fromUtf8("actionLoad_video_file"))
        self.actionRemove_all_photos = QtGui.QAction(MainWindow)
        self.actionRemove_all_photos.setObjectName(_fromUtf8("actionRemove_all_photos"))
        self.actionRemove_all_videos = QtGui.QAction(MainWindow)
        self.actionRemove_all_videos.setObjectName(_fromUtf8("actionRemove_all_videos"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionLoad_pictures)
        self.menuFile.addAction(self.actionLoad_video_file)
        self.menuFile.addAction(self.actionRemove_all_photos)
        self.menuFile.addAction(self.actionRemove_all_videos)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.connections()

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_13.setText(QtGui.QApplication.translate("MainWindow", "Delete photo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Interferogram Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Find scale ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Scale :                [ pix/mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Circle size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_12.setText(QtGui.QApplication.translate("MainWindow", "Open workspace", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_15.setText(QtGui.QApplication.translate("MainWindow", "Save scale", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "pictures", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Delete video", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Video Info:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Capture frames from video", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "seconds", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "videos", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Select an item to perform any action", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Camera ON", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "White level", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Test period", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Algorithm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "thicknes [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "C up", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "C down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "lambda [nm]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "a down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "a up", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("MainWindow", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("MainWindow", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "width [mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_5.setText(QtGui.QApplication.translate("MainWindow", "Gradient", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_6.setText(QtGui.QApplication.translate("MainWindow", "Concentration[%]", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_7.setText(QtGui.QApplication.translate("MainWindow", "Fringe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Criterion", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Static Fringe Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Photo sub- list:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Save to file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Add to list", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Time and Variable:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_3.setText(QtGui.QApplication.translate("MainWindow", "Imbalance", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4.setText(QtGui.QApplication.translate("MainWindow", "C changes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Count Time change", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("MainWindow", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_11.setText(QtGui.QApplication.translate("MainWindow", "Remove all", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_14.setText(QtGui.QApplication.translate("MainWindow", "Add all", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Time Fringe Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSettings.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_paths.setText(QtGui.QApplication.translate("MainWindow", "Edit config file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_pictures.setText(QtGui.QApplication.translate("MainWindow", "Load folder with files (photos)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_video_file.setText(QtGui.QApplication.translate("MainWindow", "Load single file (video)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_all_photos.setText(QtGui.QApplication.translate("MainWindow", "Remove all photos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_all_videos.setText(QtGui.QApplication.translate("MainWindow", "Remove all videos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

